/* This file has been automatically-generated by the grunt task requirejs-bundle; any changes to this file could be lost */
<<<<<<< HEAD
require(["theme/tz/js/tz-theme"]);
=======
require(["theme/LGA/js/LGA-theme"]);
>>>>>>> 7a835e7dbf8bcc9ed3a0ec65e1f322c0001a8439
